# Generated by Django 5.0.3 on 2024-03-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(default='places/default1.jpg', upload_to='places_images/'),
        ),
    ]
