# Generated by Django 5.0.3 on 2024-03-29 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='users/default.jpeg ', upload_to='user_photos/'),
        ),
    ]
